name: Docker related CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  audit-trivy:
    name: Trivy Scan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - docker/audit/trivy
          - docker/lint/hadolint
          - file/lint/awesome-ci
          - file/lint/checkmake
          - git/lint/awesome-ci
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: build
        run: make build DOCKER_PATH=./${{ matrix.image }} DOCKER_IMAGE=${{ matrix.image }}
      - uses: dogmatic69/actions/docker/audit/trivy@master
        with:
          image: ${{ matrix.image }}
          path: ./${{ matrix.image }}

  lint-hadolint:
    name: Trivy Scan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - docker/audit/trivy
          - docker/lint/hadolint
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: build
        run: make build DOCKER_PATH=./${{ matrix.image }} DOCKER_IMAGE=${{ matrix.image }}
      - uses: dogmatic69/actions/docker/audit/trivy@master
        with:
          image: ${{ matrix.image }}
          path: ./${{ matrix.image }}
