name: General File related CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  file-lint:
    name: General File Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - cr
          - crlf
          - trailing-newline
          - trailing-single-newline
          - trailing-space
          - utf8
          - utf8-bom
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: dogmatic69/actions/file/lint/awesome-ci@master
        with:
          command: file-${{ matrix.command }}

  makefile-lint:
    name: Makefile Lint
    runs-on: ubuntu-latest
    steps:
      - uses: dogmatic69/actions/file/lint/checkmake@master
