name: Git related CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  git-lint:
    name: Git Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command:
          - conflicts
          - ignored
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - uses: dogmatic69/actions/git/lint/awesome-ci@master
        with:
          command: git-${{ matrix.command }}
  gitleaks:
    name: GitLeaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - uses: dogmatic69/actions/git/audit/gitleaks@master
        with:
          command: git-${{ matrix.command }}
